custom_sentiment_fetch/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'custom_sentiment_fetch'
urlpatterns = [
    # route is a string contains a URL pattern
    # view refers to the view function
    # name the URL
    path(route='', view=views.custom_sentiment, name='custom_sentiment'),
    
 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'dashboard'
urlpatterns = [
    # route is a string contains a URL pattern
    # view refers to the view function
    # name the URL
    path(route='', view=views.index, name='index'),
    path('registration/', views.registration_request, name='registration'),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),
    
 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

peace_watch/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('sentiment/', include('custom_sentiment_fetch.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

custom_sentiment_fetch/models.py
from django.db import models

# Create your models here.

dashboard/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Learner(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    phone_number = models.IntegerField(blank=True)
    

custom_sentiment_fetch/views.py
from django.shortcuts import render
from custom_sentiment_fetch.apps import CustomSentimentFetchConfig
from custom_sentiment_fetch.twitter_api2 import get_tweet_sentiment
import numpy as np

# Create your views here.
def custom_sentiment(request):
    context = {}
    print(request.method)
    
    if request.method == 'GET':
        return render(request, 'custom_sentiment/custom_sentiment.html', context)
    
    elif request.method == 'POST':
        city = request.POST['city']
        query = request.POST['query']
        prediction_list =[]
        tweets = get_tweet_sentiment(city, query)
        for tweet in tweets:
            prepared_text=np.array([tweet.full_text])
            prediction_score = np.float64(CustomSentimentFetchConfig.sentiment_model.predict(prepared_text)[0][0]).item()
            prediction_list.append(prediction_score)
        if len(prediction_list) > 0:
            final_score = sum(prediction_list)/len(prediction_list)    
            prediction = assign_prediction(final_score)
            final_list = tuple(zip(tweets, prediction_list)) 
            context ={'sentiment':prediction, 'sentiment_score':final_score, 'tweet_list': final_list}
            return render(request, 'custom_sentiment/custom_sentiment.html', context)
        else:
            context = {'error': "Sorry, Unable to perform analysis for given parameters"}
            return render(request, 'custom_sentiment/custom_sentiment.html', context)   

def assign_prediction(prediction_score):
        pred_score=prediction_score
        sentiment = 'Negative'
        if(pred_score<-0.5):
            sentimentg = 'Poor'
        elif(pred_score>=-0.5 and pred_score<0.5):
            sentiment = 'Average'
        elif(pred_score>=0.5 and pred_score<1):
            sentiment = 'Good'
        elif(pred_score>=1):
            sentiment = 'Positive' 
        return sentiment

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect, HttpResponse
from django.urls import reverse
from django.views import generic
from django.contrib.auth import login, logout, authenticate
from dashboard.apps import DashboardConfig
import logging


logger = logging.getLogger(__name__)

# Create your views here.
def index(request):
    return render(request, 'dashboard/dashboard_bootstrap.html')

def registration_request(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'dashboard/user_registration_bootstrap.html', context)
    elif request.method == 'POST':
        # Check if user exists
        username = request.POST['username']
        password = request.POST['psw']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        user_exist = False
        try:
            User.objects.get(username=username)
            user_exist = True
        except:
            logger.error("New user")
        if not user_exist:
            user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name,
                                            password=password)
            login(request, user)
            return redirect("dashboard:index")
        else:
            context['message'] = "User already exists."
            return render(request, 'dashboard/user_registration_bootstrap.html', context)


def login_request(request):
    context = {}
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['psw']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('dashboard:index')
        else:
            context['message'] = "Invalid username or password."
            return render(request, 'dashboard/user_login_bootstrap.html', context)
    else:
        return render(request, 'dashboard/user_login_bootstrap.html', context)


def logout_request(request):
    logout(request)
    return redirect('dashboard:index')


custom_sentiment_fetch/templates/custom_sentiment/custom_sentiment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

    <!-- Navigation bar -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'dashboard:index' %}">Home</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}-{{ user.last_name }}@{{ user.username }}</a>
                    <a class="btn btn-link" href="{% url 'dashboard:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'dashboard:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Password" name="psw" >
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'dashboard:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container">
        <div class="card-deck">
            <div class="card" style="width: 36rem;">
                          <div class="card-body bg-light">
                              <h3 class="card-title">Custom City Sentiment Analyser</h3>
                                <p class="card-text">This is a Custom City Sentitment Analyser Powered by Twitter</p> 
                                <p class="card-text">It can be used to fetch top tweets in an Area (City) and return probable Sentiment of the place</p> 
                                
                          </div>
            </div>
        </div>
    </div>          
    <!-- Stylize Registration form -->
    {% if user.is_authenticated %}
    <form action="{% url 'custom_sentiment_fetch:custom_sentiment' %}" method="post">
        <div class="container"> <!--Style root div with .container class -->
            {% csrf_token %}
            <h1>Enter Query</h1>
            <hr>
            <div class="form-group"> <!--Style second div with .form-group class -->
                <label for="city"><b>City</b></label>
                <input type="text" class="form-control" placeholder="Enter City to Target" name="city" required> <!--Style input with .form-control class -->
                <label for="query"><b>First Name</b></label>
                <input type="text" class="form-control" placeholder="Enter Custom Query (Optional)" name="query" > <!--Style input with .form-control class -->
                <button class="btn btn-primary" type="submit">Submit</button> <!--Style button with .btn and .btn-primary class -->
            </div>
        </div>
    </form>
    {% else %}
    <div class="container">
        <div class="card-deck">
            <div class="card" style="width: 36rem;">
                          <div class="card-body bg-light">
                              <h3 class="card-title">Login To Continue</h3>
                                <p class="card-text">Please Login to access this service</p> 
                          </div>
            </div>
        </div>
    </div>
    {% endif %}
    
    {% if sentiment %}
    <div class="container">
        <div class="card-deck">
            <div class="card" style="width: 36rem;">
                          <div class="card-body bg-light">
                              <h3 class="card-title">Sentiment Detected is {{sentiment}} with score: {{sentiment_score}}</h3>
                              {% for tweet, score in tweet_list %}
                                <p class="card-text">Tweet: {{tweet.full_text}} <br>
                                Score: {{score}}</p> 
                                {% endfor %}
                            </div>

            </div>
        </div>
    </div>
    {% endif %}

    {% if error %}
    <div class="container">
        <div class="card-deck">
            <div class="card" style="width: 36rem;">
                          <div class="card-body bg-light">
                              <h3 class="card-title">{{error}}</h3>
                                <p class="card-text">Please try Again</p> 
                            </div>

            </div>
        </div>
    </div>
    {% endif %}
    


</body>

dashboard/templates/dashboard/user_login_bootstrap.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

<!-- Navigation bar -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'dashboard:index' %}">Home</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}-{{ user.last_name }}@{{ user.username }}</a>
                    <a class="btn btn-link" href="{% url 'dashboard:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'dashboard:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Password" name="psw" >
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'dashboard:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- Stylize Login form -->
    <form action="{% url 'dashboard:login' %}" method="post">
        {% csrf_token %}
        <div class="container"> <!--Style root div with .container class -->
            <h1>Login</h1>
            <div class="form-group"> <!--Style second div with .form-group class -->
              <label for="username"><b>User Name</b></label>
              <input id="username" class = "form-control" type="text" placeholder="Enter User Name: " name="username" required> <!--Style input with .form-control class -->
              <label for="psw"><b>Password</b></label>
              <input id="psw" class = "form-control" type="password"  placeholder="Enter Password: " name="psw" required> <!--Style input with .form-control class -->
            </div>
            {% if message %}
              <div class="alert alert-warning"> <!--Style the message paragraph with .alert and .alert-warning class -->
                {{ message }}
              </div>
            {% endif %}
            <button class="btn btn-primary" type="submit">Login</button> <!--Style button with .btn and .btn-primary class -->
        </div>
    </form>

</body>

dashboard/templates/dashboard/user_registration_bootstrap.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

    <!-- Navigation bar -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'dashboard:index' %}">Home</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}-{{ user.last_name }}@{{ user.username }}</a>
                    <a class="btn btn-link" href="{% url 'dashboard:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'dashboard:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Password" name="psw" >
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'dashboard:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- Stylize Registration form -->
    <form action="{% url 'dashboard:registration' %}" method="post">
        <div class="container"> <!--Style root div with .container class -->
            {% csrf_token %}
            <h1>Sign Up</h1>
            <hr>
            <div class="form-group"> <!--Style second div with .form-group class -->
                <label for="username"><b>User Name</b></label>
                <input type="text" class="form-control" placeholder="Enter User Name: " name="username" required> <!--Style input with .form-control class -->
                <label for="firstname"><b>First Name</b></label>
                <input type="text" class="form-control" placeholder="Enter First Name: " name="firstname" required> <!--Style input with .form-control class -->
                <label for="lastname"><b>Last Name</b></label>
                <input type="text" class="form-control" placeholder="Enter Last Name: " name="lastname" required> <!--Style input with .form-control class -->
                <label for="psw"><b>Password</b></label>
                <input type="password" class="form-control" placeholder="Enter Password: " name="psw" required> <!--Style input with .form-control class -->
                {% if message %}
                <div class="alert alert-warning"> <!--Style the message paragraph with .alert and .alert-warning class -->
                    {{ message }}
                </div>
                {% endif %}
                <button class="btn btn-primary" type="submit">Sign up</button> <!--Style button with .btn and .btn-primary class -->
            </div>
        </div>
    </form>

</body>